### PR TITLE
added arithmetic tests for parser

### PR DESCRIPTION
**Pull request by lillyfwang**

### CODE REVIEW

**Comment by akalicki** [comment]
liftoff

**Comment by lillyfwang** [comment]
perfectionist
what a perfectionist....see: "add newline at end of file", "add some space for readability"

**Comment by lillyfwang** [comment]
goodcall
on the parenthesis test tho...LGTM

**Comment by akalicki** [comment]
hah quality gifs - and yeah you're on to me

**Comment by lillyfwang** [comment]
i see you

**Pull request merged**
